### ISSUE TITLE
FileNotFoundException on fresh install of Umbraco and package

### ISSUE THREAD

**Issue by nickcova** [harikrishna43/UmbracoForms.Mailchimp.WorkFlow#1]
Hello,

I'm working on a brand new installation of Umbraco 7.11.1 and I installed your package via the the Developer section of the backend. Installation went through without any errors and I was also able to configure the Forms workflow task without issues. But, when I tried filling out a couple of forms, I noticed the following error showing up on my tracelog (_I removed my list ID and API Key from the message_):

```
2018-08-08 11:44:11,242 [P21552/D2/T17] ERROR Umbraco.Forms.Core.Services.WorkflowService - Form workflow 'Mailchimp Test' failed on 'Submitted' of Record with Unique ID 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' from the Form named 'Contact Form' with Unique ID 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
System.IO.FileNotFoundException: Could not load file or assembly 'MailChimp, Version=1.1.92.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'MailChimp, Version=1.1.92.0, Culture=neutral, PublicKeyToken=null'
   at UmbracoForm.MailChimp.UmbracoMacilChimpFlowType.Execute(Record record, RecordEventArgs e)
   at Umbraco.Forms.Core.Services.WorkflowService.ExecuteWorkflows(List`1 workflows, RecordEventArgs e)
```

There seems to be a file missing in my installation. According to your instructions, the only requirement for using your package is having Umbraco Forms pre-installed. Are the instructions missing something? Do I have to install additional packages?

Best regards,

**Comment by nickcova** [comment]
Ok, apparently you forgot to mention that you need to have [Mailchimp.NET](https://github.com/danesparza/MailChimp.NET) installed. That's the DLL I'm missing.
